sudo: false
language: generic
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

env:
    global:
        - TEST_LANG='python'

matrix:
    include:

        # This build will compile the LaTeX source of the paper
        - os: linux
          env: TEST_LANG='paper'

        # Linux, Python 2.7
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.11
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12

        # Linux, Python 3.5
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12

        # Linux, Python 3.6
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.11
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.12

        # OSX
        - os: osx
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12
        - os: osx
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.12

install:
    - source .ci/travis.sh

script: |
    if [[ $TEST_LANG == paper ]]
    then
      source .ci/build-paper.sh
    elif [[ $TEST_LANG == python ]]
    then
      py.test -v --cov george
    fi

after_success: |
    if [[ $TEST_LANG == python ]]
    then
      coveralls
    fi
